### ISSUE TITLE
[Media Files] Add an extensibility point to FetchMediaFilesFromContent component

### ISSUE THREAD

**Issue by roma-glushko** [magento-hackathon/m2-content-provisioning#15]
**Current Behaviour**
Currently, deployment of media files works only for media that is added by {{media}} directive. 

**Desired Behaviour**
The {{media}} directive is not enough usually to cover all CMS content management needs. On the practice, media files can be used in CMS content from widgets as well. 

It can be helpful to have an extensible point in _FetchMediaFilesFromContent_ component to be able to compose custom media file queries to be able to fetch files from different places (like custom widget parameters)

**Comment by roma-glushko** [comment]
Hi @vadimjustus as a solution, I would use the composite pattern and give consumers an ability to register custom components via di.xml. Would it work for you?

**Comment by roma-glushko** [comment]
Hi @vadimjustus this task is ready. Can you please review it?

**Comment by vadimjustus** [comment]
Hi @roma-glushko, thank you for your PR. Great job 👍
